from .contractor_tests import ContractorTestCase
from .profile_tests import ProfileTestCase
from .users_tests import UsersTestCase
from .email_tests import EmailTestCase
from .login_tests import LoginTestCase
from .change_password_tests import ChangePasswordTestCase
from .profile_tests import ProfileTestCase
from .hashtag_tests import HashtagTestCase
from .news_tests import *