# Generated by Django 3.0.8 on 2020-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='is_revoked',
            field=models.BooleanField(default=False, verbose_name='is_revoked'),
        ),
    ]
