# Generated by Django 3.0.8 on 2020-10-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.CharField(max_length=200, null=True, verbose_name='refresh_token'),
        ),
    ]
