# Generated by Django 3.0.3 on 2020-06-08 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('editor_name', models.CharField(max_length=100, verbose_name='editor name')),
                ('contact_person', models.CharField(max_length=100, verbose_name='contact person')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(help_text="hashtag's name", max_length=50, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('content', models.TextField()),
                ('contractors', models.ManyToManyField(to='crm.Contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsBurstMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('method', models.CharField(default='direct', help_text='format how to burst the news', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('character', models.CharField(default='standard', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('template', models.TextField(blank=True, help_text='Text for email template', null=True)),
                ('signature', models.TextField(blank=True, help_text='Signature in the end of email', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(help_text='Stores the name for this particular news project', max_length=50, verbose_name='project_name')),
                ('budget', models.PositiveIntegerField(default=0, help_text='Budget for the project', verbose_name='project_budget')),
                ('client', models.CharField(help_text='The name of the client for whom project is', max_length=50, verbose_name='client_name')),
                ('contractors', models.ManyToManyField(related_name='project_contractors', to='crm.Contractor')),
                ('emails', models.ManyToManyField(related_name='project_emails', to='crm.NewsEmail')),
                ('hashtags', models.ManyToManyField(related_name='project_hashtags', to='crm.Hashtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='crm\\avatar_2x.png', upload_to='crm\\users_pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.CreateModel(
            name='WaveFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('content', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.NewsEmail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostFormatList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('post_format', models.CharField(help_text='type of post for the news', max_length=20)),
                ('news_amount', models.PositiveIntegerField(default=0, help_text='Show amount of already published news', verbose_name='news_amount')),
                ('arranged_news', models.PositiveIntegerField(default=0, help_text='Shows amount of news which were arranged to publish per month', verbose_name='arranged news amount')),
                ('one_post_price', models.PositiveIntegerField(default=0, help_text='Shows the price for one post of this type', verbose_name='one post price')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsWave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('title', models.CharField(help_text='Holds the name of the title for news wave', max_length=200, verbose_name='title')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='budget')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('news_character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.NewsCharacter')),
                ('news_in_project', models.ManyToManyField(to='crm.News')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.NewsProject')),
                ('burst_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.NewsBurstMethod')),
                ('contractors', models.ManyToManyField(to='crm.Contractor')),
                ('hashtags', models.ManyToManyField(to='crm.Hashtag')),
                ('wave_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.WaveFormation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsproject',
            name='manager',
            field=models.ForeignKey(help_text='stores the key on User who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.NewsEmail'),
        ),
    ]
