# Generated by Django 3.0.3 on 2020-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_newsattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswave',
            name='post_format',
            field=models.CharField(default='', help_text='type of post for the news wave', max_length=20),
            preserve_default=False,
        ),
    ]
