# Generated by Django 3.0.3 on 2020-06-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_newswave_post_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveFormationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('file', models.FileField(upload_to='crm\\wave_formation_attachments')),
                ('wave_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.WaveFormation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
