# Generated by Django 3.0.8 on 2020-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_waveformationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsemail',
            name='codeword',
            field=models.CharField(help_text='Additional information about holder of email', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\news_attachments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main_app\\avatar_2x.png', upload_to='main_app\\users_pictures'),
        ),
        migrations.AlterField(
            model_name='waveformationattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\wave_formation_attachments'),
        ),
    ]
