# Generated by Django 3.0.8 on 2020-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20200806_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsattachment',
            name='file',
            field=models.FileField(upload_to='main_app/news_attachments'),
        ),
        migrations.AlterField(
            model_name='postformatlist',
            name='post_format',
            field=models.CharField(help_text='type of post for the news', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main_app/avatar_2x.png', upload_to='main_app/users_pictures'),
        ),
        migrations.AlterField(
            model_name='waveformationattachment',
            name='file',
            field=models.FileField(upload_to='main_app/wave_formation_attachments'),
        ),
    ]
