# Generated by Django 3.0.8 on 2020-08-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20200812_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postformatlist',
            name='post_format',
            field=models.CharField(default=None, help_text='type of post for the news', max_length=50),
        ),
    ]
