# Generated by Django 3.0.8 on 2020-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20200812_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\news_attachments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main_app\\avatar_2x.png', upload_to='main_app\\users_pictures'),
        ),
        migrations.AlterField(
            model_name='waveformationattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\wave_formation_attachments'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(help_text="client's name", max_length=70, verbose_name='name')),
                ('numbers', models.CharField(help_text="client's phone numbers", max_length=40, verbose_name='numbers')),
                ('emails', models.CharField(help_text="client's emails", max_length=70, verbose_name='emails')),
                ('price', models.PositiveIntegerField(help_text="we don't understand for what it is", verbose_name='price')),
                ('amount_publications', models.PositiveIntegerField(help_text='Displays how many publications we have to do for the client', verbose_name='amount_publish')),
                ('hashtags', models.ManyToManyField(to='crm.Hashtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
