# Generated by Django 3.0.8 on 2020-08-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20200814_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsproject',
            name='client',
            field=models.ForeignKey(help_text='The name of the client for whom project is', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Client'),
        ),
    ]
