# Generated by Django 3.0.8 on 2020-08-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20200818_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main_app\\users_pictures\\avatar_2x.png', upload_to='main_app\\users_pictures'),
        ),
        migrations.CreateModel(
            name='NewsWavePriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
