# Generated by Django 3.0.8 on 2020-08-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20200821_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newswave',
            name='contractors',
        ),
    ]
