# Generated by Django 3.0.8 on 2020-08-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_remove_newswave_contractors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPublicationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('publish', models.CharField(blank=True, help_text='Name of topic or edition which contractor publishes', max_length=200, verbose_name='publish')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractorPublicationsBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('not_publish', models.CharField(blank=True, help_text="Name of topic or edition which contractor doesn't publish", max_length=200, verbose_name='not_publish')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractorCommentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('comment', models.TextField(blank=True, help_text='Contains comment to this contractor')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contractor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
