# Generated by Django 3.0.8 on 2020-09-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
        ('crm', '0020_auto_20200831_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail_credentials',
            field=models.ForeignKey(db_column='Credentials.id', null=True, on_delete=django.db.models.deletion.CASCADE, to='email_app.Credentials'),
        ),
        migrations.AlterField(
            model_name='newsattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\news_attachments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main_app\\users_pictures\\avatar_2x.png', upload_to='main_app\\users_pictures'),
        ),
        migrations.AlterField(
            model_name='waveformationattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\wave_formation_attachments'),
        ),
    ]
