# Generated by Django 3.0.8 on 2020-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20200928_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\news_attachments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='main_app\\users_pictures\\avatar_2x.png', upload_to='main_app\\users_pictures'),
        ),
        migrations.AlterField(
            model_name='waveformationattachment',
            name='file',
            field=models.FileField(upload_to='main_app\\wave_formation_attachments'),
        ),
    ]
