# Generated by Django 3.0.8 on 2020-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20200928_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswave',
            name='contractors',
            field=models.ManyToManyField(to='crm.Contractor'),
        ),
    ]
