# Generated by Django 3.0.8 on 2020-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_newswave_contractors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waveformationattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='waveformationattachment',
            name='base_64',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='waveformationattachment',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='waveformationattachment',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
