# Generated by Django 3.0.8 on 2020-11-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_newswaveattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waveformationattachment',
            name='wave_formation',
        ),
        migrations.DeleteModel(
            name='NewsAttachment',
        ),
        migrations.DeleteModel(
            name='WaveFormationAttachment',
        ),
    ]
