# Generated by Django 3.0.8 on 2020-11-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20201117_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswaveattachment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.News'),
        ),
        migrations.AlterField(
            model_name='newswaveattachment',
            name='wave_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.WaveFormation'),
        ),
    ]
