# Generated by Django 3.0.8 on 2020-12-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20201202_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_archived',
        ),
    ]
